extend = "../barks-compleat-reader/.ruff-base.toml"

exclude = [
    "experiments",
    "scraps",
    "tools",
    "**/src/barks_ocr/utils/geometry.py",
    "**/src/barks_ocr/utils/ocr_box.py",
]

[lint]
ignore = [
    "C901", "PLR0912",
    "LOG015",  # logging
    "PLR0913",
    "TD002",
]
