extend = "../barks-compleat-reader/.ruff-base.toml"

exclude = [
    "experiments",
    "scraps",
    "**/src/barks_ocr/utils/geometry.py",
    "**/src/barks_ocr/utils/ocr_box.py",
]

[lint]
ignore = [
    "TD002",
]
