[environment]
python = "./.venv"
root = [
    "./src",
]

[src]
exclude = [
   	"**/experiments",
    "**/scraps",
    "**/tools",
    "src/barks_ocr/utils/geometry.py",
    "src/barks_ocr/utils/ocr_box.py",
    "src/barks_ocr/nano/nano_banana_panels.py",
    "src/barks_ocr/nano/nano_banana_test.py",
]
