[environment]
python = "./.venv"
root = [
    "./src",
]
extra-paths = [
    "../barks-compleat-reader/src/barks-reader/src",
    "../barks-compleat-reader/src/barks-build-comic-images/src",
    "../barks-compleat-reader/src/barks-fantagraphics/src",
    "../barks-compleat-reader/src/comic-utils/src",
]

[src]
exclude = [
    "**/scraps",
    "**/tools",
    "src/utils/geometry.py",
    "src/nano-banana-panels-ai.py",
    "src/nano-banana-test.py",
    "src/nano-banana-batch.py",
    "src/nano-banana-batch-results.py",
]
