[environment]
python = "./.venv"
root = [
    "./src",
]

[src]
exclude = [
   	"**/experiments",
    "**/scraps",
    "**/tools",
    "src/utils/geometry.py",
    "src/nano-banana-panels-to-ai.py",
    "src/nano-banana-test.py",
]
